version: '3.8'

services:
  db:
    image: postgres:16
    container_name: UnitedLibraDB
    environment:
      POSTGRES_USER: Fion1x
      POSTGRES_PASSWORD: nikitakravs
      POSTGRES_DB: LibraryDB
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
